import { getPatients } from "@/lib/data";
import { getCachedContext } from "@/lib/context-cache";
import { PatientListTable } from "@/components/PatientListTable";
import { AssessAllButton } from "@/components/AssessAllButton";
import type { Readiness } from "@/lib/types";

// Always render fresh so newly-cached readiness shows after "Assess".
export const dynamic = "force-dynamic";

export default async function Home() {
  const patients = await getPatients();

  const readinessById: Record<string, Readiness | undefined> = {};
  for (const p of patients) {
    readinessById[p.id] = getCachedContext(p.id)?.readiness;
  }

  const admissions = patients.filter((p) => p.isAdmission);
  const unassessedAdmissions = admissions
    .filter((p) => !readinessById[p.id])
    .map((p) => p.id);

  return (
    <main className="mx-auto w-full max-w-6xl flex-1 px-6 py-8">
      <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">
            Patient list
          </h1>
          <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
            {patients.length} patients · {admissions.length} admissions ·
            discharge readiness generated by Claude from each chart
          </p>
        </div>
        <AssessAllButton ids={unassessedAdmissions} />
      </div>

      <PatientListTable patients={patients} readinessById={readinessById} />

      <p className="mt-4 text-xs text-zinc-400 dark:text-zinc-500">
        Prototype using fully synthetic data (Abridge / Synthea). Discharge
        context is AI-generated decision support — not a substitute for clinical
        judgment.
      </p>
    </main>
  );
}
